<article id="callforpapers">
    <h1>Call for papers</h1>
    <h2>Become a speaker of the conference</h2>
    <h3>The deadline to receive proposals is May 20th</h3>
    <h4>Do you want to speak at the conference?</h4>
    <p>Talks about JavaScript, Mobile, User Experience, NodeJS, JQuery and anything related to Javascript are welcome!</br>We would like an international conference so English talks are preferred!</br>We would like questions after your session. So please think about session's duration not more than 35-40 min.</p>
      <p> Remember, the deadline to receive <a href="//docs.google.com/spreadsheet/viewform?formkey=dHZwWWU3VHFlSVBja1V0UVlnUmgyalE6MA" target="_blank">proposals</a> is May 20th. </p>
    <div class="call-papers">
      <a href="//docs.google.com/spreadsheet/viewform?formkey=dHZwWWU3VHFlSVBja1V0UVlnUmgyalE6MA" class="btn" target="_blank">Call for papers</a>
    </div>
    
</article>