<article id="fiesta1">
    <h1>Conference Dinner: The Garden party</h1>
    <div class="clearfix">
      <div class="main">
        <h2>The Irish Rover</h2>
        <h3>Friday, 5th (21:00h)</h3>
        <h4 class="lead"> <br/>
              Avenida de Brasil,7<br/>
              Upstairs!<br/>
              Near Metro Line 10: Santiago Bernabeu station or Cuzco station<br/>
              <strong>Please, bring your event identifier</strong></h4>
              <br/>
      </div>
      <div class="visual">
        <div class="map">
            <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=The+irish+rover+Avenida+de+Brasil,+7,+Madrid,+Spain&amp;aq=&amp;sll=40.454948,-3.693659&amp;sspn=0.004294,0.010428&amp;ie=UTF8&amp;hq=The+irish+rover&amp;hnear=Av+de+Brasil,+7,+28020+Madrid,+Comunidad+de+Madrid,+Spain&amp;t=m&amp;ll=40.454099,-3.693981&amp;spn=0.005715,0.00912&amp;z=16&amp;iwloc=A&amp;output=embed"></iframe>
        </div>
      </div>
    </div>
  </article>

  <article id="fiesta2">
    <h1>Atlassian Party</h1>
    <div class="clearfix">
      <div class="main">
        <h2>Areia Colonial Chillout</h2>
        <h3>Saturday, 6th (21:00h)
        <h4 class="lead">
              Calle Hortaleza, 92<br/>
              Metro Line 5, Chueca station or Metro Lines 1 and 10, Tribunal station<br/>
              <strong>Please, bring your event identifier</strong></h4>
              <br/>

      </div>
      <div class="visual">
        <div class="map">
            <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=AREIA+COLONIAL+CHILLOUT,+Calle+Hortaleza,+92,+Madrid,+Spain&amp;aq=0&amp;oq=Areia+Colonial+Chillout+Calle+Hortaleza,+92&amp;sll=40.454842,-3.693949&amp;sspn=0.004294,0.010428&amp;ie=UTF8&amp;hq=AREIA+COLONIAL+CHILLOUT,&amp;hnear=Calle+Hortaleza,+92,+28004+Madrid,+Spain&amp;t=m&amp;ll=40.423494,-3.69808&amp;spn=0.005717,0.00912&amp;z=16&amp;iwloc=A&amp;output=embed"></iframe>
        </div>
      </div>
    </div>
  </article>