<a name="jobsboard"></a>
<section  class="sponsors clearfix" id="job_board">
  <div class="wrap">
    <h1>Jobs board</h1>

    <article>
      <h2>Desarrollador FRONT END (JAVASCRIPT, HTML, CSS)</h2>
      <h3>Company: Paradigma tecnológico</h3>
      <p>
        En estos momentos buscamos a un desarrollador FRONT END con amplia experiencia en HTML5, CSS3, JAVASCRIPT... con capacidad de comunicación y con ganas de seguir creciendo personal y profesionalmente. Formará parte de un equipo altamente cualificado y especializado y tendrá la posibilidad de participar en proyectos técnicamente muy interesantes.
      </p>

      <div class="more">
        <p>El trabajo del día a día es participar junto con el resto del equipo de Front en el diseño y maquetación de los proyectos que se estén llevando a cabo, e interactuar con el resto del equipo de desarrollo Back para definir bien las necesidades y el buen hacer del proyecto.</p>

        <h4>Para hacer bien este trabajo creemos que es importante ser una persona:</h4>
        <ul>
          <li>Con don de gentes y aptitudes para el trabajo en equipo.</li>
          <li>Facilidad para la comunicación oral y escrita con interlocutores de áreas técnicas.</li>
          <li>Responsable.</li>
          <li>Con iniciativa y creatividad.</li>
          <li>Capacidad de análisis del detalle y minuciosidad.</li>
          <li>E inquietud para adquirir nuevos conocimientos.</li>
        </ul>

        <p><strong>* ¡¡¡NECESARIO PRESENTAR PORTFOLIO EXCEPCIONAL!!! *</strong></p>

        <h4>Si te interesa formar parte de nuestro equipo podrás beneficiarte de:</h4>
        <ul>
          <li>Trabajar con las últimas tecnologías.</li>
          <li>Hay posibilidad de flexibilidad horaria.</li>
          <li>Disponemos de Jornada intensiva los meses de Julio y Agosto.</li>
          <li>y un inmejorable ambiente de trabajo</li>
          <li>La remuneración se establece en función de la experiencia aportada por cada uno.</li>
          <li>Valoramos a las personas de manera individualizada.</li>
          <li>Incorporación en una compañía competitiva y en continua evolución.</li>
          <li>Ofrecemos la posibilidad de tener beneficios sociales.</li>
          <li>Y la Posibilidad de crecer profesionalmente</li>
        </ul>

        <p>Puedes contactar en : <a href="mailto:rrhh@paradigmatecnologico.com">rrhh@paradigmatecnologico.com</a></p>
      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

    <article>
      <h2>UX - CONSULTOR DE USABILIDAD</h2>
      <h3>Company: Paradigma tecnológico</h3>
      <p>
        En estos momentos buscamos a UN CONSULTOR DE USABILIDAD para incorporarse al equipo de UX.
      </p>

      <div class="more">
        <h4>El trabajo del día a día es:</h4>
        <ul>
          <li>Definir las prioridades de diseño del proyecto en el que te incorpores.</li>
          <li>Aterrizar ideas y añadir valor a las mismas.</li>
          <li>Defender la calidad del producto y la innovación.</li>
          <li>Definir la arquitectura de información y comportamiento (interacción, flujos de procesos, etc..).</li>
          <li>Escribir y mantener la documentación sobre especificaciones y comportamiento del producto.</li>
          <li>Generar presentaciones y ofertas de respuesta a RFP.</li>
          <li>Velar por la calidad y coherencia de la experiencia de usuario.</li>
          <li>Presentar y defender en público tu trabajo.</li>
        </ul>

        <p>Valoraremos la capacidad para definir las actividades y planes de acción en el ámbito del marketing y de la comunicación.</p>
        <p>Así como la capacidad de diseñar la interfaz del producto final, con atención tanto al copy como a todos los elementos propios del diseño visual (layout, color, tipografía…)</p>
        <p>Y la de gestión de equipos/proyectos bajo metodologías ágiles.</p>

        <h4>Para hacer bien este trabajo creemos que es importante ser una persona:</h4>
        <ul>
          <li>Con don de gentes y aptitudes para el trabajo en equipo.</li>
          <li>Facilidad para la comunicación oral y escrita con interlocutores de áreas técnicas y de marketing.</li>
          <li>Responsable.</li>
          <li>Con iniciativa y creatividad.</li>
          <li>Capacidad de análisis del detalle y minuciosidad.</li>
          <li>E inquietud para adquirir nuevos conocimientos.</li>
        </ul>

        <p><strong>* ¡¡¡NECESARIO PRESENTAR PORTFOLIO EXCEPCIONAL!!! *</strong></p>

        <h4>Si te interesa formar parte de nuestro equipo podrás beneficiarte de:</h4>
        <ul>
          <li>Trabajar con las últimas tecnologías.</li>
          <li>Hay posibilidad de flexibilidad horaria.</li>
          <li>Disponemos de Jornada intensiva los meses de Julio y Agosto.</li>
          <li>y un inmejorable ambiente de trabajo</li>
          <li>La remuneración se establece en función de la experiencia aportada por cada uno.</li>
          <li>Valoramos a las personas de manera individualizada.</li>
          <li>Incorporación en una compañía competitiva y en continua evolución.</li>
          <li>Ofrecemos la posibilidad de tener beneficios sociales.</li>
          <li>Y la Posibilidad de crecer profesionalmente</li>
        </ul>

        <p>Puedes contactar en : <a href="mailto:rrhh@paradigmatecnologico.com">rrhh@paradigmatecnologico.com</a></p>
      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

    <article>
      <h2>Desarrollador Sr JavaScript</h2>
      <h3>Company: Adesis Netlife</h3>
      <p>Detalles de la oferta en <a href="http://www.infojobs.net/seleccionar/desarrollador-sr-javascript/of-i01c8604bda4b74944f32b1ac282175" rel="nofollow">Infojobs</a></p>

      <div class="more">
        <p>Mínimo 4 años de experiencia</p>

        <p>Profesionales inquietos con curiosidad y pasión por la innovación y la calidad del software y con una visión pragmática de los resultados.</p>

        <p>Experiencia en desarrollo web interaccionando con aplicaciones de servidor en Java utilizando técnicas y herramientas de referencia.</p>

        <p>Capaz de escuchar al cliente, asumir la responsabilidad de sus encargos, coordinar el equipo y responder ágilmente</p>

        <p>Experiencia demostrable en: - Programación de javascript y experiencia en frameworks de javascript como JQuery, Backbone, Undercores, PhantomJS, etc Conocimientos avanzados de javascript (closures, hoisting, CommonJS, etc.) - Experiencia en gestión de la calidad en desarrollos javascript con JSLint, JSHint, JSCoverage, etc. - Experiencia en optimizaciones de recursos estáticos web con herramientas como Google Closure, YUI Compressor, OptiPNG, etc. - Experiencia o conocimientos en desarrollo en base a pruebas unitarias en javascript.</p>
      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

    <article>
      <h2>UX Senior Manager</h2>
      <h3>Company: Adesis Netlife</h3>
      <p>Detalles de la oferta en <a href="http://www.infojobs.net/seleccionar/ux-senior-manager/of-i4ce0acf5154a8c8974a06efd031329" rel="nofollow">Infojobs</a></p>

      <div class="more">
        <p>¿Te apasiona la usabilidad y experiencia de usuario? ¿Tienes un don para inspirar a un equipo de profesionales de diseño de interacción, arquitectura de la información y consultores de UX? ¿Estás listo para ayudar a dar forma al destino de una empresa joven, dinámica y bien posicionada?</p>

        <h4>Estamos buscando un Responsable de UX para:</h4>
        <ul>
          <li>Desarrollar propuestas innovadoras que ayuden al crecimiento del departamento de UX.</li>
          <li>Colaborar para definir los productos y servicios.</li>
          <li>Definir eficazmente ideas conceptuales, fundamentos de diseño y los detalles del proceso centrado en el usuario.</li>
          <li>Coordinarse con equipos multidisciplinares para entregar el producto final.</li>
          <li>Presentaciones a clientes, control de proyectos y gestión de equipos.</li>
        </ul>

      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

     <article>
      <h2>C++/Javascript Mobile Platform Developer for Open Web Device </h2>
      <h3>Company: Telefónica I+D</h3>
      <p>
        Can you code with your eyes closed?<br/>
        Do you know code like it´s your mother tongue?<br/>
        Love programming and creating software?<br/>
        Want to build amazing products that make a difference in the digital world?<br/>
        Enjoy working hard with highly skilled developers to reach team objectives?<br/>
        Willing to share your knowledge and learn new technologies and effective<br/> ways to develop the best software?<br/>
        Are you an active member in amazing open source project?<br/>
        If this sounds like you (or someone you know), keep reading…<br/>

      </p>

      <div class="more">
        <p><strong>We are looking for a passionate, enthusiastic and skilled server side software engineer / developer to be part of the team building Open Web Device, a joint Mozilla & Telefónica Digital development for a device in which any developer could create the entire UX through HTML/CSS/JS.</strong></p>

        <h4>Responsabilities</h4>

        <ul>
          <li>Design, develop and maintain software components making technical decisions about technologies, data structures, algorithms, programmatic solutions, etc.</li>
 
          <li>Write clean, scalable and fast performing code according to guidelines and quality standards (SOLID principles, code readability, pattern use, coupling, cyclomatic complexity etc.), including development and maintenance of automated unit tests.</li>
 
          <li>Participate as part of development team in sprint planning and review meetings according to Agile principles, analyzing features specifications (user stories) translating them into development tasks and estimating those tasks to build sprint backlog.</li>
 
          <li>Review other developers’ code according to code review mechanisms followed at Telefónica Digital.</li>
 
          <li>Pursue the generation of common components and best practices, fostering the reuse of technology and knowledge across Telefónica Digital software products, specifically the ones in the technological area where he/she is assigned.</li>
 
          <li>Research and recommend new technologies as well as software libraries (including open source), models and tools.</li>

        </ul> 
        <h4>Qualifications</h4>
        <p>BS/MS Degree in Computer Science or related degree or equivalent work experience in software development.</p>

        <h4>Technical Competences</h4>
        <p>Strong knowledge of:</p>
        <ul>
          <li>Software technologies: architecture and development</li>
          <li>Object oriented architectures, data structures, algorithms and concurrent programming</li>
          <li>C++</li>
          <li>Javascript, specifically for backend/platform development (i.e. XPCShell/Gecko platform)</li>

        </ul>
        <h4>Experience in</h4>
        <ul>
          <li>Developing low level modules/modifications for current mobile operating systems (Android and/or Firefox OS preferably)</li>
          <li>Low level architecture of current mobile operating systems</li>
        </ul>      
 
       <h4> Significant knowledge in the following technologies will be a plus</h4>
        <ul>
          <li>Node.js</li>
          <li>Front-end technologies: HTML5/CSS3/Javascript/DOM</li>
          <li>Database design, SQL (specifically MySQL) and NoSQL (specifically MongoDB)</li>
          <li>TCP/IP, HTTP and network programming</li>
          <li>High availability/performance/scalable architectures</li>
          <li>Implementation and deployment of complex systems/ modules/components</li>
          <li>TDD</li>
        </ul>

        <p>Workplace: Indiferent</p>
      </div>
      <p>If you are interested in this position, please send us an email to <a href="mailto:hrtalent@tid.es">hrtalent@tid.es</a></p>
      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>


     <article>
      <h2>Front End Developers</h2>
      <h3>Company: Telefónica I+D</h3>
      <p>
        Can you code with your eyes closed?<br/>
        Do you know code like it´s your mother tongue?<br/>
        Love programming and creating software?<br/>
        Want to build amazing products that make a difference in the digital world?<br/>
        Enjoy working hard with highly skilled developers to reach team objectives?<br/>
        Willing to share your knowledge and learn new technologies and effective<br/> ways to develop the best software?<br/>
        Are you an active member in amazing open source project?<br/>
        If this sounds like you (or someone you know), keep reading…<br/>

      </p>

      <div class="more">
        <p><strong>We are looking for passionate, enthusiastic and skilled software engineers / developers that can thrive in a fast-paced, exciting software business and build innovative services and technologies empowering the best software products in Telefónica Digital.
Responsibilities</strong></p>

        <h4>Responsabilities</h4>

        <ul>
          <li>Design, develop and maintain software components making technical decisions about technologies, data structures, algorithms, programmatic solutions, etc.</li>
 
          <li>Write clean, scalable and fast performing code according to guidelines and quality standards (SOLID principles, code readability, pattern use, coupling, cyclomatic complexity etc.), including development and maintenance of automated unit tests.</li>
 
          <li>Participate as part of development team in sprint planning and review meetings according to Agile principles, analyzing features specifications (user stories) translating them into development tasks and estimating those tasks to build sprint backlog.</li>
 
          <li>Review other developers’ code according to code review mechanisms followed at Telefónica Digital.</li>
 
          <li>Pursue the generation of common components and best practices, fostering the reuse of technology and knowledge across Telefónica Digital software products, specifically the ones in the technological area where he/she is assigned.</li>
 
          <li>Research and recommend new technologies as well as software libraries (including open source), models and tools.</li>
          <li>
            Take part of Technical Councils for other software products different from the one he/she is working for, providing valuable feedback in a proactive way in order to ensure that the best technical decisions are taken
          </li> 
        </ul> 
        <h4>Qualifications</h4>
        <p>BS/MS Degree in Computer Science or related degree or equivalent work experience in software development.</p>

        <h4>Technical Competences</h4>
        <p>Fluency in the following languages and frameworks</p>
        <ul>
          <li>HTML (specifically HTML5), CSS (specifically CSS3) and Javascript
          <li>jQuery and angular.js</li>
          <li>JSON and XML</li>
          <li>Wijmo components</li>

        </ul>

        <h4>Sound knowledge of</h4>
        <ul>
          <li>Software development paradigms, architectural patterns, design patterns and development principles and practices</li>
          <li>Client/server programming</li>
          <li>RESTful architectures</li>
          <li>Other Javascript frameworks (e.g. ExtJS)</li>
          <li>HTTP protocol, webruntime, environments and architecture</li>


        </ul> 
        <h4>Experience in</h4>
        <ul>
          <li>Developing in Javascript, CSS3 and HTML5, with special focus on UI</li>
          <li>Building Object Oriented web applications with Javascript</li>
          <li>Developing complex consumer web applications</li>
          <li>Designing and developing WebApps will be a plus</li>
          <li>Delivering web applications for most used browsers (IE, FF, Chrome, Safari)</li>

        </ul>      
 
       <h4> Significant knowledge in the following technologies will be a plus</h4>
        <ul>
            <li>Javascript TDD/BDD frameworks (e.g. Jasmine)</li>
            <li>Security issues and software vulnerabilities</li>
            <li>Server Side programming languages/frameworks, specifically Javascript/node.js</li>
            <li>Language/frameworks to build web applications for cross-platform mobile devices (e.g. Phonegap)</li>

        </ul>
      </div>
      <p>If you are interested in this position, please send us an email to <a href="mailto:hrtalent@tid.es">hrtalent@tid.es</a></p>
      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

    <article>
      <h2>Senior Interaction Designer </h2>
      <h3>Company: Telefónica I+D</h3>
      <p>We are looking for a highly motivated and talented Senior Interaction Designer to join the team of Interaction Designers, Visual Designers and Researchers.
      </p>

      <div class="more">
        <p>Designers and researchers work in collaborative teams with project leads, strategists, engineers and domain experts to generate innovative concepts and solutions for multiple screens: TV, PC, mobile and more.<br/>
The Senior Interaction Designer will collaborate with researchers on generating insights, leading ideation sessions with interdisciplinary teams, and articulate product concepts, interaction philosophy and models, as well as use cases and benefits of ideas. 
The individual will need to work conceptually using models and story boards, as well as pragmatically through detailed interaction flows and specifications.
</p>

        <h4>Responsabilities</h4>

        <ul>
          <li>Deliver superior & industry leading product design for specific projects and initiatives.</li>
          <li>Collaborate with researchers on generating customer insights.</li>
          <li>Communicate, document, and represent product concepts, user scenarios and designs to team members, senior management and key stakeholders. </li>
          <li>Expertly craft documentation to represent the team's vision around user experience, including: storyboards, schematics, style guides, movies, PPTs and prototypes.</li>
          <li>Develop information architecture, interaction design, wire frames and software UI, that meet user needs, user tasks, marketing requirements and business objectives.</li>
          <li>Create interaction design guidelines and principles to be applied across global product solutions.</li>
          <li>Partner closely with Product and Initiative leaders and engineers to ensure delivery of quality solution that meets all requirements and provides a consistent product design approach.</li>
          <li>Work with the rest of the Research, Visual and Interaction design team to articulate methods and best practices, and share them with the larger TID community.</li>
          <li>Support multiple projects in parallel; organize and manage assignments in a dynamic environment.</li>

        </ul> 
        <h4>Experience</h4>
        
        <ul>
          <li>Experience designing for different input technologies and user environments, including key three screens: Mobile, PC, TV.</li>
          <li>Excellent command of: user experience methods, design principles, problem-framing skills and research methods.</li>
          <li>Excellent ability to deliver mental models, concept sketches, workflows, information architecture and UI components.</li>
          <li>Strong visual design sense, along with prototyping skills on interactive visualization technologies such as Adobe Suite, Flash, DHTML, CSS, AJAX, etc.</li>
          <li>Demonstrated ability to articulate a vision for design and deliver on it.</li>
          <li>Experience working in a rapid application development environment using appropriate tools and techniques. Experience with agile development is a plus. </li>
          <li>Location: Madrid</li>
        </ul> 
        
      </div>
      <p>If you are interested in this position, please send us an email to <a href="mailto:hrtalent@tid.es">hrtalent@tid.es</a></p>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

    <article>
      <h2>Senior Visual Designer</h2>
      <h3>Company: Telefónica I+D</h3>
      <p>We are looking for a highly motivated and talented Senior Visual Designer/Creative Director to join the team of Interaction Designers, Visual Designers and Researchers in Telefonica I+D (Madrid, Spain). 
      </p>

      <div class="more">
        <p>Designers and researchers work in collaborative teams with project leads, strategists, engineers and domain experts to generate innovative concepts and solutions for multiple screens: TV, PC, mobile and more.<br/>
        The Senior Visual Designer/Creative Director will collaborate with researchers on generating insights, leading ideation sessions with interdisciplinary teams, and articulate product concepts, user scenarios and story boards, as well as the vision for the user experience. <br/>
        The individual will need to be able to illustrate concepts in real time using narrative, sketches, prototypes, as well as generate multiple visual and experimental directions that bring brand values and attributes to live. 

</p>

        <h4>Responsabilities</h4>

        <ul>
          <li>Deliver superior & industry leading visual design for specific projects and initiatives. 
          <li>Collaborate with researchers and interaction designers or service design leads on generating customer insights.
          <li>Create an evolving, global visual and experiential language that works across platforms and takes country-specific variances into consideration.
          <li>Work with other visual designers in the team to create cohesive, world-class products and services. 
          <li>Communicate, document, and represent product concepts, user scenarios and visual designs to team members, senior management and key stakeholders. 
          <li>Expertly craft documentation to represent the team's vision around user experience, including: storyboards, visual designs, style guides, movies, PPTs and prototypes. 
          <li>Work closely with engineering teams in an Agile framework to bring implement optimally performing graphics across multiple screens.
          <li>Establish visual and experimental tool kit that can be shared with partners, developers, third parties.
          <li>Partner closely with Product and Initiative leaders and engineers to ensure delivery of quality solution that meets all requirements and provides a coherent, quality experience.
          <li>Work with the rest of the Research, Visual and Interaction design team to articulate methods and best practices, and share them with the larger TID community. 
          <li>Support multiple projects in parallel; organize and manage assignments in a dynamic environment.</li>


        </ul> 
        <h4>Experience</h4>
        
        <ul>
          <li>Experience designing for different input technologies and user environments, including key three screens: Mobile, PC, TV.</li>
          <li>Excellent command of: user experience methods, design principles, visual design trends.</li>
          <li>Excellent ability to deliver visual designs, temporal experiences, concept sketches, UI components.</li>
          <li>Flash and knowledge of other media/animation/sound tools a plus.</li>
          <li>Demonstrated ability to articulate a vision for design and deliver on it.</li>
          <li>Experience working in a rapid application development environment using appropriate tools and techniques. Experience with agile development is a plus.</li>

        </ul> 
        <h4>Others</h4>
        <ul>
          <li>Master's in design, media communications or related fields desired. 
          <li>Minimum BA/BS degree in Communication Design or Media Communications with extensive work experience.</li>
          <li>Portfolio review required.</li>
          <li>Location: Madrid</li>

        </ul>
      </div>
      <p>If you are interested in this position, please send us an email to <a href="mailto:hrtalent@tid.es">hrtalent@tid.es</a></p>
      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

    <article>
      <h2>Software Engineer (Javascript API Developer)</h2>
      <h3>Company: Spotify</h3>
      <p>We, the Spotify API team ( <a href="http://www.spotify.com/about/apps/" target="_blank">http://www.spotify.com/about/apps/</a> ) are looking for a skilled and driven Javascript programmer with demonstrable knowledge in designing and building cross-platform APIs and frameworks. Our team is responsible for designing and building a new breed of APIs for our developers and users, and we are looking for a new team member who has a "users-first" mindset and a passion for building tested and well-documented APIs and frameworks.
      </p>

      <div class="more">
        <p>Native JavaScript proficiency is a requirement, although we do work across different platforms and languages. A familiarity with languages such as C++, Java or Objective-C is a plus, although not a requirement.<br/>

        You should be willing to relocate to (or are already located in) Stockholm, Sweden.</p>

        <h4>Responsabilities</h4>

        <ul>
          <li>Participate in the design and implementation of the new Spotify API.</li>
          <li>Support other teams when integrating with deliverables of your team.</li>
          <li>Maintain good relationships with other development teams so as to best know how to serve their needs and make them more effective.</li>
        </ul> 
        <h4>Qualifications</h4>
        
        <ul>
          <li>Outstanding engineering talent proven by great work results/experience, interesting hobby projects, open source contributions or superior academic results</li>

          <li>Demonstrable proficiency in JavaScript</li>
          <li>Passion for writing testable and tested code</li>
          <li>Ability to write well-documented code and explaining methods in good English</li>
          <li>Familiarity with C++, C, Objective-C and/or Java is a plus but not required</li>
          <li>Self-motivation, but ability to excel in a team-based environment. Strong initiative skills and enthusiasm</li>
        </ul> 
        <p>
          People who meet us tend to comment on our energy, and the passion we have for what we are doing. We hope it’s infectious! At such a fast moving start up you’ll find opportunities rather than boundaries in every single role.<br/>

          When applying, please provide all documents in PDF or TXT format and include links to stuff you've worked on with descriptions of your contributions or design process. If you use GitHub or similar please provide references to that as well.

        </p>
      </div>
      <p>If you are interested in this position, Apply here: <a href="https://www.spotify.com/se/jobs/apply/?id=oKepXfw4" target="_blank">https://www.spotify.com/se/jobs/apply/?id=oKepXfw4</a></p>
      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>

      <article>
      <h2>Software Engineer (Payment Developer)</h2>
      <h3>Company: Spotify</h3>
      <p>You’re located in (or willing to relocate to) Stockholm, Sweden.<br/>

We want to connect millions of people with their favorite songs and create a service that people love to use. We believe that music should be easily accessible and that listening to music will make peoples live richer. We want to create a win-win situation for people who love listening to music and people who love creating music.
      </p>

      <div class="more">
        <p>The payment systems are a highly critical area for Spotify. We want to make it's as easy as possible to pay for legal music streaming, regardless of our users preferred payment method. As a part of the payment team you will be responsible for integrating our backend systems with our public facing web-sites and -applications.<br/>

        We put emphasis on building well-tested and stable systems at Spotify and that is especially true for our payment team. Experience and interest in unit- and integration-testing is a must for this position as you will work closely with our Quality Assurance-personnel to make sure we have a stable foundation for our payment services.<br/>

        In this role you will be involved in both PHP and Python development, as well as work on our presentation layer using standard web technology such as JavaScript, CSS, HTML.</p>

        <h4>Responsabilities</h4>

        <ul>
          <li>Build and develop new payment integrations across a multitude of different applications</li>
<li>Create rock solid unit- and integration tests</li>
<li>Deployment of software in the test and production environment</li>
<li>Collaboration with other stakeholders within Spotify</li>
<li>Analyze customer flows and improve the customer experience</li>
<li>Contributing to our web-dev architecture discussions</li>
<li>Setting up and configuring servers in a Debian environment using Puppet</li>
        </ul> 
        <h4>Requirements</h4>
        
        <ul>
          <li>Coding is one of your passions in life</li>
<li>You are an expert PHP-developer with long experience in working with highly scalable web solutions</li>
<li>Expert knowledge of web technologies (PHP, HTML5, CSS3, JS)</li>
<li>Ability to write well-abstracted, reusable code</li>
<li>Python experience or a keen interest in learning it</li>
<li>Good knowledge about Linux</li>
<li>Nothing from low level hacking to system design intimidates you</li>
        </ul> 
        <p>
          You should have an insatiable appetite for learning new things and improving existing ones. If you’re the right one for us, you pay attention to details and take great pride in your work. <br/>

          People who meet us tend to comment on our energy, and the passion we have for what we’re doing. We hope it’s infectious! At such a fast moving start up you’ll find opportunities rather than boundaries in every single role.
        </p>
      </div>
      <p>If you are interested in this position, Apply here: <a href="https://www.spotify.com/se/jobs/apply/?id=o9YmXfwa" target="_blank">https://www.spotify.com/se/jobs/apply/?id=o9YmXfwa</a></p>
      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>
  </div>
</section>
