<a name="jobsboard"></a>
<section  class="sponsors clearfix" id="job_board">
  <div class="wrap">
    <h1>Jobs board</h1>

    <article>
      <h2>Desarrollador FRONT END (JAVASCRIPT, HTML, CSS)</h2>
      <h3>Company: Paradigma tecnológico</h3>
      <p>
        En estos momentos buscamos a un desarrollador FRONT END con amplia experiencia en HTML5, CSS3, JAVASCRIPT... con capacidad de comunicación y con ganas de seguir creciendo personal y profesionalmente. Formará parte de un equipo altamente cualificado y especializado y tendrá la posibilidad de participar en proyectos técnicamente muy interesantes.
      </p>

      <div class="more">
        <p>El trabajo del día a día es participar junto con el resto del equipo de Front en el diseño y maquetación de los proyectos que se estén llevando a cabo, e interactuar con el resto del equipo de desarrollo Back para definir bien las necesidades y el buen hacer del proyecto.</p>

        <h4>Para hacer bien este trabajo creemos que es importante ser una persona:</h4>
        <ul>
          <li>Con don de gentes y aptitudes para el trabajo en equipo.</li>
          <li>Facilidad para la comunicación oral y escrita con interlocutores de áreas técnicas.</li>
          <li>Responsable.</li>
          <li>Con iniciativa y creatividad.</li>
          <li>Capacidad de análisis del detalle y minuciosidad.</li>
          <li>E inquietud para adquirir nuevos conocimientos.</li>
        </ul>

        <p><strong>* ¡¡¡NECESARIO PRESENTAR PORTFOLIO EXCEPCIONAL!!! *</strong></p>

        <h4>Si te interesa formar parte de nuestro equipo podrás beneficiarte de:</h4>
        <ul>
          <li>Trabajar con las últimas tecnologías.</li>
          <li>Hay posibilidad de flexibilidad horaria.</li>
          <li>Disponemos de Jornada intensiva los meses de Julio y Agosto.</li>
          <li>y un inmejorable ambiente de trabajo</li>
          <li>La remuneración se establece en función de la experiencia aportada por cada uno.</li>
          <li>Valoramos a las personas de manera individualizada.</li>
          <li>Incorporación en una compañía competitiva y en continua evolución.</li>
          <li>Ofrecemos la posibilidad de tener beneficios sociales.</li>
          <li>Y la Posibilidad de crecer profesionalmente</li>
        </ul>

        <p>Puedes contactar en : <a href="mailto:rrhh@paradigmatecnologico.com">rrhh@paradigmatecnologico.com</a></p>
      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

    <article>
      <h2>UX - CONSULTOR DE USABILIDAD</h2>
      <h3>Company: Paradigma tecnológico</h3>
      <p>
        En estos momentos buscamos a UN CONSULTOR DE USABILIDAD para incorporarse al equipo de UX.
      </p>

      <div class="more">
        <h4>El trabajo del día a día es:</h4>
        <ul>
          <li>Definir las prioridades de diseño del proyecto en el que te incorpores.</li>
          <li>Aterrizar ideas y añadir valor a las mismas.</li>
          <li>Defender la calidad del producto y la innovación.</li>
          <li>Definir la arquitectura de información y comportamiento (interacción, flujos de procesos, etc..).</li>
          <li>Escribir y mantener la documentación sobre especificaciones y comportamiento del producto.</li>
          <li>Generar presentaciones y ofertas de respuesta a RFP.</li>
          <li>Velar por la calidad y coherencia de la experiencia de usuario.</li>
          <li>Presentar y defender en público tu trabajo.</li>
        </ul>

        <p>Valoraremos la capacidad para definir las actividades y planes de acción en el ámbito del marketing y de la comunicación.</p>
        <p>Así como la capacidad de diseñar la interfaz del producto final, con atención tanto al copy como a todos los elementos propios del diseño visual (layout, color, tipografía…)</p>
        <p>Y la de gestión de equipos/proyectos bajo metodologías ágiles.</p>

        <h4>Para hacer bien este trabajo creemos que es importante ser una persona:</h4>
        <ul>
          <li>Con don de gentes y aptitudes para el trabajo en equipo.</li>
          <li>Facilidad para la comunicación oral y escrita con interlocutores de áreas técnicas y de marketing.</li>
          <li>Responsable.</li>
          <li>Con iniciativa y creatividad.</li>
          <li>Capacidad de análisis del detalle y minuciosidad.</li>
          <li>E inquietud para adquirir nuevos conocimientos.</li>
        </ul>

        <p><strong>* ¡¡¡NECESARIO PRESENTAR PORTFOLIO EXCEPCIONAL!!! *</strong></p>

        <h4>Si te interesa formar parte de nuestro equipo podrás beneficiarte de:</h4>
        <ul>
          <li>Trabajar con las últimas tecnologías.</li>
          <li>Hay posibilidad de flexibilidad horaria.</li>
          <li>Disponemos de Jornada intensiva los meses de Julio y Agosto.</li>
          <li>y un inmejorable ambiente de trabajo</li>
          <li>La remuneración se establece en función de la experiencia aportada por cada uno.</li>
          <li>Valoramos a las personas de manera individualizada.</li>
          <li>Incorporación en una compañía competitiva y en continua evolución.</li>
          <li>Ofrecemos la posibilidad de tener beneficios sociales.</li>
          <li>Y la Posibilidad de crecer profesionalmente</li>
        </ul>

        <p>Puedes contactar en : <a href="mailto:rrhh@paradigmatecnologico.com">rrhh@paradigmatecnologico.com</a></p>
      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

    <article>
      <h2>Desarrollador Sr JavaScript</h2>
      <h3>Company: Adesis Netlife</h3>
      <p>Detalles de la oferta en <a href="http://www.infojobs.net/seleccionar/desarrollador-sr-javascript/of-i01c8604bda4b74944f32b1ac282175" rel="nofollow">Infojobs</a></p>

      <div class="more">
        <p>Mínimo 4 años de experiencia</p>

        <p>Profesionales inquietos con curiosidad y pasión por la innovación y la calidad del software y con una visión pragmática de los resultados.</p>

        <p>Experiencia en desarrollo web interaccionando con aplicaciones de servidor en Java utilizando técnicas y herramientas de referencia.</p>

        <p>Capaz de escuchar al cliente, asumir la responsabilidad de sus encargos, coordinar el equipo y responder ágilmente</p>

        <p>Experiencia demostrable en: - Programación de javascript y experiencia en frameworks de javascript como JQuery, Backbone, Undercores, PhantomJS, etc Conocimientos avanzados de javascript (closures, hoisting, CommonJS, etc.) - Experiencia en gestión de la calidad en desarrollos javascript con JSLint, JSHint, JSCoverage, etc. - Experiencia en optimizaciones de recursos estáticos web con herramientas como Google Closure, YUI Compressor, OptiPNG, etc. - Experiencia o conocimientos en desarrollo en base a pruebas unitarias en javascript.</p>
      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

    <article>
      <h2>UX Senior Manager</h2>
      <h3>Company: Adesis Netlife</h3>
      <p>Detalles de la oferta en <a href="http://www.infojobs.net/seleccionar/ux-senior-manager/of-i4ce0acf5154a8c8974a06efd031329" rel="nofollow">Infojobs</a></p>

      <div class="more">
        <p>¿Te apasiona la usabilidad y experiencia de usuario? ¿Tienes un don para inspirar a un equipo de profesionales de diseño de interacción, arquitectura de la información y consultores de UX? ¿Estás listo para ayudar a dar forma al destino de una empresa joven, dinámica y bien posicionada?</p>

        <h4>Estamos buscando un Responsable de UX para:</h4>
        <ul>
          <li>Desarrollar propuestas innovadoras que ayuden al crecimiento del departamento de UX.</li>
          <li>Colaborar para definir los productos y servicios.</li>
          <li>Definir eficazmente ideas conceptuales, fundamentos de diseño y los detalles del proceso centrado en el usuario.</li>
          <li>Coordinarse con equipos multidisciplinares para entregar el producto final.</li>
          <li>Presentaciones a clientes, control de proyectos y gestión de equipos.</li>
        </ul>

      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

     <article>
      <h2>C++/Javascript Mobile Platform Developer for Open Web Device </h2>
      <h3>Company: Telefónica I+D</h3>
      <p>
        Can you code with your eyes closed?<br/>
        Do you know code like it´s your mother tongue?<br/>
        Love programming and creating software?<br/>
        Want to build amazing products that make a difference in the digital world?<br/>
        Enjoy working hard with highly skilled developers to reach team objectives?<br/>
        Willing to share your knowledge and learn new technologies and effective<br/> ways to develop the best software?<br/>
        Are you an active member in amazing open source project?<br/>
        If this sounds like you (or someone you know), keep reading…<br/>

      </p>

      <div class="more">
        <p><strong>We are looking for a passionate, enthusiastic and skilled server side software engineer / developer to be part of the team building Open Web Device, a joint Mozilla & Telefónica Digital development for a device in which any developer could create the entire UX through HTML/CSS/JS.</strong></p>

        <h4>Responsabilities</h4>

        <ul>
          <li>Design, develop and maintain software components making technical decisions about technologies, data structures, algorithms, programmatic solutions, etc.</li>
 
          <li>Write clean, scalable and fast performing code according to guidelines and quality standards (SOLID principles, code readability, pattern use, coupling, cyclomatic complexity etc.), including development and maintenance of automated unit tests.</li>
 
          <li>Participate as part of development team in sprint planning and review meetings according to Agile principles, analyzing features specifications (user stories) translating them into development tasks and estimating those tasks to build sprint backlog.</li>
 
          <li>Review other developers’ code according to code review mechanisms followed at Telefónica Digital.</li>
 
          <li>Pursue the generation of common components and best practices, fostering the reuse of technology and knowledge across Telefónica Digital software products, specifically the ones in the technological area where he/she is assigned.</li>
 
          <li>Research and recommend new technologies as well as software libraries (including open source), models and tools.</li>

        </ul> 
        <h4>Qualifications</h4>
        <p>BS/MS Degree in Computer Science or related degree or equivalent work experience in software development.</p>

        <h4>Technical Competences</h4>
        <p>Strong knowledge of:</p>
        <ul>
          <li>Software technologies: architecture and development</li>
          <li>Object oriented architectures, data structures, algorithms and concurrent programming</li>
          <li>C++</li>
          <li>Javascript, specifically for backend/platform development (i.e. XPCShell/Gecko platform)</li>

        </ul>
        <h4>Experience in</h4>
        <ul>
          <li>Developing low level modules/modifications for current mobile operating systems (Android and/or Firefox OS preferably)</li>
          <li>Low level architecture of current mobile operating systems</li>
        </ul>      
 
       <h4> Significant knowledge in the following technologies will be a plus</h4>
        <ul>
          <li>Node.js</li>
          <li>Front-end technologies: HTML5/CSS3/Javascript/DOM</li>
          <li>Database design, SQL (specifically MySQL) and NoSQL (specifically MongoDB)</li>
          <li>TCP/IP, HTTP and network programming</li>
          <li>High availability/performance/scalable architectures</li>
          <li>Implementation and deployment of complex systems/ modules/components</li>
          <li>TDD</li>
        </ul>

        <p>Workplace: Indiferent</p>
      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>


     <article>
      <h2>Front End Developers</h2>
      <h3>Company: Telefónica I+D</h3>
      <p>
        Can you code with your eyes closed?<br/>
        Do you know code like it´s your mother tongue?<br/>
        Love programming and creating software?<br/>
        Want to build amazing products that make a difference in the digital world?<br/>
        Enjoy working hard with highly skilled developers to reach team objectives?<br/>
        Willing to share your knowledge and learn new technologies and effective<br/> ways to develop the best software?<br/>
        Are you an active member in amazing open source project?<br/>
        If this sounds like you (or someone you know), keep reading…<br/>

      </p>

      <div class="more">
        <p><strong>We are looking for passionate, enthusiastic and skilled software engineers / developers that can thrive in a fast-paced, exciting software business and build innovative services and technologies empowering the best software products in Telefónica Digital.
Responsibilities</strong></p>

        <h4>Responsabilities</h4>

        <ul>
          <li>Design, develop and maintain software components making technical decisions about technologies, data structures, algorithms, programmatic solutions, etc.</li>
 
          <li>Write clean, scalable and fast performing code according to guidelines and quality standards (SOLID principles, code readability, pattern use, coupling, cyclomatic complexity etc.), including development and maintenance of automated unit tests.</li>
 
          <li>Participate as part of development team in sprint planning and review meetings according to Agile principles, analyzing features specifications (user stories) translating them into development tasks and estimating those tasks to build sprint backlog.</li>
 
          <li>Review other developers’ code according to code review mechanisms followed at Telefónica Digital.</li>
 
          <li>Pursue the generation of common components and best practices, fostering the reuse of technology and knowledge across Telefónica Digital software products, specifically the ones in the technological area where he/she is assigned.</li>
 
          <li>Research and recommend new technologies as well as software libraries (including open source), models and tools.</li>
          <li>
            Take part of Technical Councils for other software products different from the one he/she is working for, providing valuable feedback in a proactive way in order to ensure that the best technical decisions are taken
          </li> 
        </ul> 
        <h4>Qualifications</h4>
        <p>BS/MS Degree in Computer Science or related degree or equivalent work experience in software development.</p>

        <h4>Technical Competences</h4>
        <p>Fluency in the following languages and frameworks</p>
        <ul>
          <li>HTML (specifically HTML5), CSS (specifically CSS3) and Javascript
          <li>jQuery and angular.js</li>
          <li>JSON and XML</li>
          <li>Wijmo components</li>

        </ul>

        <h4>Sound knowledge of</h4>
        <ul>
          <li>Software development paradigms, architectural patterns, design patterns and development principles and practices</li>
          <li>Client/server programming</li>
          <li>RESTful architectures</li>
          <li>Other Javascript frameworks (e.g. ExtJS)</li>
          <li>HTTP protocol, webruntime, environments and architecture</li>


        </ul> 
        <h4>Experience in</h4>
        <ul>
          <li>Developing in Javascript, CSS3 and HTML5, with special focus on UI</li>
          <li>Building Object Oriented web applications with Javascript</li>
          <li>Developing complex consumer web applications</li>
          <li>Designing and developing WebApps will be a plus</li>
          <li>Delivering web applications for most used browsers (IE, FF, Chrome, Safari)</li>

        </ul>      
 
       <h4> Significant knowledge in the following technologies will be a plus</h4>
        <ul>
            <li>Javascript TDD/BDD frameworks (e.g. Jasmine)</li>
            <li>Security issues and software vulnerabilities</li>
            <li>Server Side programming languages/frameworks, specifically Javascript/node.js</li>
            <li>Language/frameworks to build web applications for cross-platform mobile devices (e.g. Phonegap)</li>

        </ul>
      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>
  </div>
</section>
