<section class="sponsors clearfix" id="job_board">
  <div class="wrap">
    <h1>Jobs board</h1>

    <article>
      <h2>Desarrollador FRONT END (JAVASCRIPT, HTML, CSS)</h2>
      <h3>Company: Paradigma tecnológico</h3>
      <p>
        En estos momentos buscamos a un desarrollador FRONT END con amplia experiencia en HTML5, CSS3, JAVASCRIPT... con capacidad de comunicación y con ganas de seguir creciendo personal y profesionalmente. Formará parte de un equipo altamente cualificado y especializado y tendrá la posibilidad de participar en proyectos técnicamente muy interesantes.
      </p>

      <div class="more">
        <p>El trabajo del día a día es participar junto con el resto del equipo de Front en el diseño y maquetación de los proyectos que se estén llevando a cabo, e interactuar con el resto del equipo de desarrollo Back para definir bien las necesidades y el buen hacer del proyecto.</p>

        <h4>Para hacer bien este trabajo creemos que es importante ser una persona:</h4>
        <ul>
          <li>Con don de gentes y aptitudes para el trabajo en equipo.</li>
          <li>Facilidad para la comunicación oral y escrita con interlocutores de áreas técnicas.</li>
          <li>Responsable.</li>
          <li>Con iniciativa y creatividad.</li>
          <li>Capacidad de análisis del detalle y minuciosidad.</li>
          <li>E inquietud para adquirir nuevos conocimientos.</li>
        </ul>

        <p><strong>* ¡¡¡NECESARIO PRESENTAR PORTFOLIO EXCEPCIONAL!!! *</strong></p>

        <h4>Si te interesa formar parte de nuestro equipo podrás beneficiarte de:</h4>
        <ul>
          <li>Trabajar con las últimas tecnologías.</li>
          <li>Hay posibilidad de flexibilidad horaria.</li>
          <li>Disponemos de Jornada intensiva los meses de Julio y Agosto.</li>
          <li>y un inmejorable ambiente de trabajo</li>
          <li>La remuneración se establece en función de la experiencia aportada por cada uno.</li>
          <li>Valoramos a las personas de manera individualizada.</li>
          <li>Incorporación en una compañía competitiva y en continua evolución.</li>
          <li>Ofrecemos la posibilidad de tener beneficios sociales.</li>
          <li>Y la Posibilidad de crecer profesionalmente</li>
        </ul>

        <p>Puedes contactar en : <a href="mailto:rrhh@paradigmatecnologico.com">rrhh@paradigmatecnologico.com</a></p>
      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

    <article>
      <h2>UX - CONSULTOR DE USABILIDAD</h2>
      <h3>Company: Paradigma tecnológico</h3>
      <p>
        En estos momentos buscamos a UN CONSULTOR DE USABILIDAD para incorporarse al equipo de UX.
      </p>

      <div class="more">
        <h4>El trabajo del día a día es:</h4>
        <ul>
          <li>Definir las prioridades de diseño del proyecto en el que te incorpores.</li>
          <li>Aterrizar ideas y añadir valor a las mismas.</li>
          <li>Defender la calidad del producto y la innovación.</li>
          <li>Definir la arquitectura de información y comportamiento (interacción, flujos de procesos, etc..).</li>
          <li>Escribir y mantener la documentación sobre especificaciones y comportamiento del producto.</li>
          <li>Generar presentaciones y ofertas de respuesta a RFP.</li>
          <li>Velar por la calidad y coherencia de la experiencia de usuario.</li>
          <li>Presentar y defender en público tu trabajo.</li>
        </ul>

        <p>Valoraremos la capacidad para definir las actividades y planes de acción en el ámbito del marketing y de la comunicación.</p>
        <p>Así como la capacidad de diseñar la interfaz del producto final, con atención tanto al copy como a todos los elementos propios del diseño visual (layout, color, tipografía…)</p>
        <p>Y la de gestión de equipos/proyectos bajo metodologías ágiles.</p>

        <h4>Para hacer bien este trabajo creemos que es importante ser una persona:</h4>
        <ul>
          <li>Con don de gentes y aptitudes para el trabajo en equipo.</li>
          <li>Facilidad para la comunicación oral y escrita con interlocutores de áreas técnicas y de marketing.</li>
          <li>Responsable.</li>
          <li>Con iniciativa y creatividad.</li>
          <li>Capacidad de análisis del detalle y minuciosidad.</li>
          <li>E inquietud para adquirir nuevos conocimientos.</li>
        </ul>

        <p><strong>* ¡¡¡NECESARIO PRESENTAR PORTFOLIO EXCEPCIONAL!!! *</strong></p>

        <h4>Si te interesa formar parte de nuestro equipo podrás beneficiarte de:</h4>
        <ul>
          <li>Trabajar con las últimas tecnologías.</li>
          <li>Hay posibilidad de flexibilidad horaria.</li>
          <li>Disponemos de Jornada intensiva los meses de Julio y Agosto.</li>
          <li>y un inmejorable ambiente de trabajo</li>
          <li>La remuneración se establece en función de la experiencia aportada por cada uno.</li>
          <li>Valoramos a las personas de manera individualizada.</li>
          <li>Incorporación en una compañía competitiva y en continua evolución.</li>
          <li>Ofrecemos la posibilidad de tener beneficios sociales.</li>
          <li>Y la Posibilidad de crecer profesionalmente</li>
        </ul>

        <p>Puedes contactar en : <a href="mailto:rrhh@paradigmatecnologico.com">rrhh@paradigmatecnologico.com</a></p>
      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

    <article>
      <h2>Desarrollador Sr JavaScript</h2>
      <h3>Company: Adesis Netlife</h3>
      <p>Detalles de la oferta en <a href="http://www.infojobs.net/seleccionar/desarrollador-sr-javascript/of-i01c8604bda4b74944f32b1ac282175" rel="nofollow">Infojobs</a></p>

      <div class="more">
        <p>Mínimo 4 años de experiencia</p>

        <p>Profesionales inquietos con curiosidad y pasión por la innovación y la calidad del software y con una visión pragmática de los resultados.</p>

        <p>Experiencia en desarrollo web interaccionando con aplicaciones de servidor en Java utilizando técnicas y herramientas de referencia.</p>

        <p>Capaz de escuchar al cliente, asumir la responsabilidad de sus encargos, coordinar el equipo y responder ágilmente</p>

        <p>Experiencia demostrable en: - Programación de javascript y experiencia en frameworks de javascript como JQuery, Backbone, Undercores, PhantomJS, etc Conocimientos avanzados de javascript (closures, hoisting, CommonJS, etc.) - Experiencia en gestión de la calidad en desarrollos javascript con JSLint, JSHint, JSCoverage, etc. - Experiencia en optimizaciones de recursos estáticos web con herramientas como Google Closure, YUI Compressor, OptiPNG, etc. - Experiencia o conocimientos en desarrollo en base a pruebas unitarias en javascript.</p>
      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>

    <article>
      <h2>Desarrollador Sr JavaScript</h2>
      <h3>Company: Adesis Netlife</h3>
      <p>Detalles de la oferta en <a href="http://www.infojobs.net/seleccionar/ux-senior-manager/of-i4ce0acf5154a8c8974a06efd031329" rel="nofollow">Infojobs</a></p>

      <div class="more">
        <p>¿Te apasiona la usabilidad y experiencia de usuario? ¿Tienes un don para inspirar a un equipo de profesionales de diseño de interacción, arquitectura de la información y consultores de UX? ¿Estás listo para ayudar a dar forma al destino de una empresa joven, dinámica y bien posicionada?</p>

        <h4>Estamos buscando un Responsable de UX para:</h4>
        <ul>
          <li>Desarrollar propuestas innovadoras que ayuden al crecimiento del departamento de UX.</li>
          <li>Colaborar para definir los productos y servicios.</li>
          <li>Definir eficazmente ideas conceptuales, fundamentos de diseño y los detalles del proceso centrado en el usuario.</li>
          <li>Coordinarse con equipos multidisciplinares para entregar el producto final.</li>
          <li>Presentaciones a clientes, control de proyectos y gestión de equipos.</li>
        </ul>

      </div>

      <p><a href="javascript:void(0)" class="btn js-more readmore">Read more</a></p>
    </article>
  </div>
</section>