<article id="pointsofinterest">
    <h1>More information</h1>
    <div class="clearfix">
      <div class="main">
        <h2>Points of Interest</h2>
        <h4 class="lead">You can find some points of interest related to the conference venue and parties</h4>
        <p>You can see more details if you make zoom on the map</p>
        <p>Open <a target="_blank"
        href="http://goo.gl/maps/uLwvy">points of interest</a> in a new window to edit it.
    </p>
      </div>
      <div class="visual">
        <div class="map">
            <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps/ms?msid=217278818591617484150.0004e04df2b593e01af6a&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=40.446425,-3.702049&amp;spn=0.091446,0.145912&amp;z=12&amp;output=embed"></iframe>
        </div>
      </div>
    </div>
  </article>