<section class="showreel">
  <div class="shooreel-main">
    <h1>We are proud to announce <a href="">Douglas Crockford</a> and <a href="">Alex Rauschmayer</a> as two of our speakers</h1>
    <div class="btn-wrap">
      <a href="" class="btn-l">PRE-REGISTER</a>
    </div>
    <h2>More to be anounced soon <br>Stay tunned!</h2>
  </div>
  <aside class="photos">
    <img src="img/showreel_douglas_alex.png" alt="">
  </aside>
</section>