<section class="showreel">
  <div class="shooreel-main">
    <h1>We are proud to announce <span>Douglas Crockford</span>, <span>Axel Rauschmayer</span> and <span>Reg Braithwaite</span> as three of our speakers</h1>
    <div class="btn-wrap">
      <a href="//eepurl.com/tFgBH" class="btn-l" target="_blank">PRE-REGISTER</a>
    </div>
    <h2>More to be anounced soon <span>Stay tuned!</span></h2>
  </div>
  <aside class="photos">
    <img src="img/showreels/douglas_axel_reg.png" alt="">
  </aside>
</section>