<section class="sponsors clearfix" id="sponsors">
  <div class="wrap">
    <ul class="platinium">
       <li>&nbsp;<a href="/sponsors.html">Make it happen again: Become a sponsor</a></li>
    </ul>
    <ul class="gold">
       <li>&nbsp;</li>
    </ul>
    <ul class="gold">
       <li>&nbsp;</li>
    </ul>
    <ul class="silver">
       <li>&nbsp;</li>
    </ul>
    <ul class="supporter">
       <li>&nbsp;</li>
    </ul>
  </div>
</section>
