<section class="sponsors clearfix" id="sponsors">
  <div class="wrap">
    <ul class="platinium">
      <li><a href="http://www.microsoft.com/spain" target="_blank"><img src="img/sponsors/microsoft.png" alt="Microsoft"></a></li>
    </ul>
    <ul class="gold">
      <li><a href="//www.plainconcepts.com/" target="_blank"><img src="img/sponsors/plain_concepts.gif" alt="Plain Concepts"></a></li>
      <li><a href="//www.adesis.com/" target="_blank"><img src="img/sponsors/adesis.jpg" alt="Adesis"></a></li>
      <li><a href="//www.intel.com/" target="_blank"><img src="img/sponsors/intel_logo.png" alt="Intel"></a></li>
    </ul>
    <ul class="gold">
      <li><a href="http://www.atlassian.com/" target="_blank"><img src="img/sponsors/atlassian.png" alt="Atlassian"></a></li>
      <li><a href="//www.mozilla.org/" target="_blank"><img src="img/sponsors/mozilla.gif" alt="Mozilla"></a></li>
      <li><a href="//www.fictizia.com/" target="_blank"><img src="img/sponsors/fictizia.gif" alt="Fictizia"></a></li>
      <li><a href="https://www.spotify.com" target="_blank"><img src="img/sponsors/spotify.jpg" alt="Spotify"></a></li>
      <li><a href="https://www.github.com" target="_blank"><img src="img/sponsors/github.jpg" alt="GitHub"></a></li>
    </ul>
    <ul class="silver">
       <li><a href="//www.paradigmatecnologico.com/" target="_blank"><img src="img/sponsors/paradigma_tecnologico.gif" alt="Paradigma tecnológico"></a></li>
       <li><a href="//www.softonic.com/" target="_blank"><img src="img/sponsors/softonic.gif" alt="Softonic"></a></li>
       <li><a href="//www.prezi.com/" target="_blank"><img src="img/sponsors/prezi.jpg" alt="Prezi"></a></li>
       <li>&nbsp;</li>
    </ul>
    <ul class="supporter">
       <li><a href="//www.upsam.es/" target="_blank"><img src="img/sponsors/upsam.jpg" alt="UPSAM"></a></li>
       <li>&nbsp;</li>
       <li>&nbsp;</li>
    </ul>
  </div>
</section>