<section class="sponsors clearfix" id="sponsors">
  <div class="wrap">
    <ul class="platinium">
      <li><a href=""><img src="img/partners/holder_l.png" alt=""></a></li>
      <li><a href=""><img src="img/partners/holder_l.png" alt=""></a></li>
      <li><a href=""><img src="img/partners/holder_l.png" alt=""></a></li>
    </ul>
    <ul class="gold">
      <li><a href=""><img src="img/partners/holder_m.png" alt=""></a></li>
      <li><a href=""><img src="img/partners/holder_m.png" alt=""></a></li>
      <li><a href=""><img src="img/partners/holder_m.png" alt=""></a></li>
      <li><a href=""><img src="img/partners/holder_m.png" alt=""></a></li>
    </ul>
    <ul class="silver">
      <li><a href=""><img src="img/partners/holder_s.jpg" alt=""></a></li>
      <li><a href=""><img src="img/partners/holder_s.jpg" alt=""></a></li>
      <li><a href=""><img src="img/partners/holder_s.jpg" alt=""></a></li>
      <li><a href=""><img src="img/partners/holder_s.jpg" alt=""></a></li>
      <li><a href=""><img src="img/partners/holder_s.jpg" alt=""></a></li>
      <li><a href=""><img src="img/partners/holder_s.jpg" alt=""></a></li>
    </ul>
  </div>
</section>