<article id="venue">
    <h1>Venue</h1>
    <div class="clearfix">
      <div class="main">
        <h2>Universidad Pontificia de Salamanca (Campus Madrid)</h2>
        <h3>Conferences</h3>
        <h4 class="lead">The conference will be held at Universidad Pontificia de Salamanca</h4>
        <p>The Madrid Campus of the Pontifical University of Salamanca - UPSAM, is located in the university city of Madrid, very near of the heart of the city, with metro and bus lines at the door of the premises.</p>
        <p>Address:Paseo de Juan XXIII, 3  28040 Madrid</p>
        <p>Metro Line 6: Metropolitano Station</p>
        <p>You can find below a map with some points of interest</p>
      </div>
      <div class="visual">
        <div class="map">
            <iframe width="100%" height="240" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.es/maps/ms?hl=es&amp;gl=es&amp;ie=UTF8&amp;oe=UTF8&amp;msa=0&amp;msid=107782206193532469952.00048885a1081d726dc92&amp;ll=40.445167,-3.719977&amp;spn=0,0&amp;output=embed" id="googlemap"></iframe>
        </div>
      </div>
    </div>
    <ul class="gallery">
      <li><div class="img"><img src="img/venue/upscm_03.jpg"></div></li>
      <li><div class="img"><img src="img/venue/upscm_02.jpg"></div></li>
      <li><div class="img"><img src="img/venue/upscm_01.jpg"></div></li>
    </ul>
  </article>